services:
  - type: web
    name: task-tool-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:socket_app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
